# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Franco A. Alvarado
description: > # this means to ignore newlines until "baseurl:"
  The online resume and portfolio Franco A. Alvarado
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.francopub.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: francofaa
linkedin_username: franco-alvarado
copyright: Franco A. Alvarado
available: true
future: false
# Build settings
markdown: kramdown
port: 4002
version: 2.0
theme: 
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  - 
    scope:
      path: "blog"
      type: "posts"
    values:
      layout: "post"
      author: "Franco"
      roll: "blog"
  -
    scope:
      path: "projects"
    values:
      layout: "project"
      roll: "projects"
  - 
    scope: 
      path: "recipe"
    values:
      layout: "recipe"

permalink: blog/:year/:month/:day/:title/
sass:
  style: compressed
